// Interface automatically generated by schemas-to-ts

export interface Homepage {
  id: number;
  attributes: {
    Header: string;
  };
}
export interface Homepage_Plain {
  id: number;
  Header: string;
}

export interface Homepage_NoRelations {
  id: number;
  Header: string;
}

export interface Homepage_AdminPanelLifeCycle {
  id: number;
  Header: string;
}
