// Interface automatically generated by schemas-to-ts

export interface Article {
  id: number;
  attributes: {
    Title: string;
  };
}
export interface Article_Plain {
  id: number;
  Title: string;
}

export interface Article_NoRelations {
  id: number;
  Title: string;
}

export interface Article_AdminPanelLifeCycle {
  id: number;
  Title: string;
}
